name: Build and Deploy to server
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Deployment

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: '1.2.4'

      - name: Build project
        run: |
          bun install
          bun run build

      - name: Copy files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          target: "/home/${{ secrets.SSH_USERNAME }}/han-gun/"
          overwrite: true
          strip_components: 1